version: '3'
services:
  db:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
  web:
    build: .
    volumes:
      - .:/app
    command: bundle exec rails s
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - REDIS_URL=redis://redis:6379
      - RAILS_LOG_TO_STDOUT=true
  sidekiq:
    image: web
    command: bundle exec sidekiq -q default -q mailers -q health_checks
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - REDIS_URL=redis://redis:6379
      - RAILS_LOG_TO_STDOUT=true
    depends_on:
      - web
      - db
      - redis
volumes:
  pg-data:
  redis-data:
